name: Train Rasa Model (linux/amd64)

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Train model inside rasa/rasa:3.6.15 container
        run: |
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}/rasa:/app \
            rasa/rasa:3.6.15 train \
            --config /app/config.yml \
            --domain /app/domain.yml \
            --data /app/data \
            --out /app/models \
            --fixed-model-name cloud-model
          sudo chmod 644 ${{ github.workspace }}/rasa/models/cloud-model.tar.gz

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloud-model
          path: rasa/models/cloud-model.tar.gz
          retention-days: 7
